//@ts-check

const allIcons = {
  android: 'android',
  apple: 'apple',
  arrow_left: 'arrow_left',
  arrow_right: 'arrow_right',
  calendar: 'calendar',
  check: 'check',
  close: 'close',
  copy: 'copy',
  download: 'download',
  edit: 'edit',
  file: 'file',
  filter: 'filter',
  gear: 'gear',
  label: 'label',
  lock: 'lock',
  navigate_bottom: 'navigate_bottom',
  navigate_left: 'navigate_left',
  navigate_right: 'navigate_right',
  navigate_up: 'navigate_up',
  remove: 'remove',
  reorder: 'reorder',
  search: 'search',
  sort_az: 'sort_az',
  uncheck: 'uncheck',
  view_gallery: 'view_gallery',
  view_list: 'view_list',
  admin: 'admin',
  burger: 'burger',
  cbx: 'cbx',
  displays: 'displays',
  mgr: 'mgr',
  ops: 'ops',
  pod: 'pod',
  promos: 'promos',
  settings: 'settings',
  sts: 'sts',
  taps: 'taps',
  beer: 'beer',
  cocktails: 'cocktails',
  spirits: 'spirits',
  wine: 'wine',
};

export default allIcons;
